### ISSUE TITLE
Issue installing fresh setup with GNOME Extensions

### ISSUE THREAD

**Issue by danrayfr** [basecamp/omakub#351]
Currently, encountering issue with new setup installation. Receiving error on GNome Extensions, ```
HTTPSConnectionPool(host='extensions.gnome.org', port=443). Max retries Max retries exceeded with url: /extension-info/?uuid=tactile%40lundal.io&shell_version=46.0 (│
│Caused by ResponseError('too many 503 error responses'))                                                                                                           │
│urllib3.exceptions.ResponseError: too many 503 error responses                                                                                                     │
│                                                                                                                                                                   │
│The above exception was the direct cause of the following exception:                                                                                               │
│                                                                                                                                                                   │
│Traceback (most recent call last):                                                                                                                                 │
│  File "/home/danrayfr/.local/share/pipx/venvs/gnome-extensions-cli/lib/python3.12/site-packages/requests/adapters.py", line 667, in send                          │
│    resp = conn.urlopen(                                                                                                                                           │
│           ^^^^^^^^^^^^^                                                                                                                                           │
│  File "/home/danrayfr/.local/share/pipx/venvs/gnome-extensions-cli/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen                  │
│    return self.urlopen(                                                                                                                                           │
│           ^^^^^^^^^^^^^                                                                                                                                           │
│  File "/home/danrayfr/.local/share/pipx/venvs/gnome-extensions-cli/lib/python3.12/site-packages/urllib3/connectionpool.py", line 944, in urlopen                  │
│    return self.urlopen(                                                                                                                                           │
│           ^^^^^^^^^^^^^                                                                                                                                           │
│  File "/home/danrayfr/.local/share/pipx/venvs/gnome-extensions-cli/lib/python3.12/site-packages/urllib3/connectionpool.py", line 934, in urlopen                  │
│    retries = retries.increment(method, url, response=response, _pool=self)                                                                                        │
│              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                        │
│  File "/home/danrayfr/.local/share/pipx/venvs/gnome-extensions-cli/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment                    │
│    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]                                                                                  │
│    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                            │
│urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='extensions.gnome.org', port=443): Max retries exceeded with url: /extension-info/?uuid=tactile%40lundal│
│.io&shell_version=46.0 (Caused by ResponseError('too many 503 error responses'))                                                                                   │
│                                                                                                                                                                   │
│During handling of the above exception, another exception occurred:                                                                                                │
│                                                                                                                                                                   │
│Traceback (most recent call last):                      
```                         

It seems the issue is within the GNome backend, isn't it? 

![Screenshot from 2024-12-05 05-25-33](https://github.com/user-attachments/assets/35a72439-eec9-4907-bd48-be4591a51a4c)

Also, there are dev experiencing similar issue on Reddit. Just sharing it here: https://www.reddit.com/r/omakub/comments/1h5vs1f/install_fails_for_gnome_extensions/

Regards,

**Comment by ninjadanray** [comment]
![Screenshot 2024-12-05 at 05 50 16](https://github.com/user-attachments/assets/7e1197e6-0958-45d8-9d45-4aa972304c40)

As of 05:51 Dec 5, PH time.

**Comment by danrayfr** [comment]
I was able to complete the setup by running the remaining script in the omakub/install/desktop from the point of error:

https://github.com/basecamp/omakub/blob/master/install/desktop/set-gnome-extensions.sh
https://github.com/basecamp/omakub/blob/master/install/desktop/set-gnome-hotkeys.sh
https://github.com/basecamp/omakub/blob/master/install/desktop/set-gnome-settings.sh
https://github.com/basecamp/omakub/blob/master/install/desktop/set-gnome-theme.sh
https://github.com/basecamp/omakub/blob/master/install/desktop/ulauncher.sh

Not sure if this is recommended, however, from what I understand I think this completed the fix. Still receiving the issue on gnome extension, just try it again and again.

**Comment by dhh** [comment]
I just did a clean install without issues. Must have been a temporary issue with gnome.org.
